export const projects = [
  {
    id: 'cursed-relic-hunter-3d', repo: 'cursed-relic-hunter-3d', branch: 'main',
    title: '저주받은 유물 사냥꾼', eyebrow: '3D FPS · 로그라이트', category: 'web',
    description: '유적을 탐험하고 유물을 모으며 세 지역의 보스에 도전하는 1인칭 게임.',
    tags: ['Three.js', 'TypeScript', '게임'], icon: '✦', tone: 'violet',
    preview: 'play/cursed-relic-hunter-3d/index.html', featured: true,
  },
  {
    id: 'chagoknyang', repo: 'chagoknyang', branch: 'main',
    title: '차곡냥', eyebrow: '고양이 퍼즐', category: 'web',
    description: '같은 고양이 네 마리를 한 상자에 모으는 아기자기한 퍼즐.',
    tags: ['HTML', '퍼즐', 'PWA'], icon: '🐈', tone: 'peach',
    preview: 'play/chagoknyang/index.html', featured: true,
  },
  {
    id: 'unforgotten-night', repo: 'unforgotten-night', branch: 'main',
    title: '지워지지 않은 밤', eyebrow: '데스크톱 추리', category: 'web',
    description: '중고 컴퓨터에 남은 기록을 조사하고 사건의 진상을 찾는 추리 게임.',
    tags: ['JavaScript', '추리', '스토리'], icon: '☾', tone: 'indigo',
    preview: 'play/unforgotten-night/index.html', featured: true,
  },
  {
    id: 'siwangjeon', repo: 'siwangjeon', branch: 'main',
    title: '시왕전', eyebrow: '덱빌더 · 로그라이크', category: 'mobile',
    description: '저승 49일, 열 명의 시왕 앞에서 업으로 심판받는 턴제 카드 게임.',
    tags: ['Flutter', 'Dart', '게임'], icon: '十', tone: 'crimson', featured: true,
  },
  {
    id: 'dokkaebi-market', repo: 'dokkaebi-market', branch: 'main',
    title: '도깨비 장터', eyebrow: '합성 퍼즐', category: 'mobile',
    description: '콩에서 시작해 장터를 키우고 손님의 주문과 이야기를 완성하는 게임.',
    tags: ['Flutter', 'Dart', '퍼즐'], icon: '✿', tone: 'amber',
  },
  {
    id: 'haesol-metro', repo: 'haesol-metro', branch: 'main',
    title: '지하철 노선 복구', eyebrow: '선로 퍼즐', category: 'mobile',
    description: '가상 도시 해솔시의 선로를 놓아 출발역과 목적역을 잇는 게임.',
    tags: ['Flutter', 'Dart', '퍼즐'], icon: '◉', tone: 'teal',
  },
  {
    id: 'moru-keugi', repo: 'moru-keugi', branch: 'main',
    title: '모루 키우기', eyebrow: '대장간 클리커', category: 'mobile',
    description: '대장간을 성장시키고 오프라인 보상과 환생을 관리하는 모바일 게임.',
    tags: ['React Native', 'Expo', '게임'], icon: '⚒', tone: 'orange',
  },
  {
    id: 'moneybook', repo: 'moneybook', branch: 'main',
    title: '영수증 가계부', eyebrow: '생활 도구', category: 'mobile',
    description: '영수증 사진을 휴대폰 안에서 읽고 확인한 내역을 기록하는 가계부.',
    tags: ['Flutter', 'OCR', '오프라인'], icon: '▤', tone: 'mint',
  },
  {
    id: 'dungeon-auto-legion', repo: 'Dungeon-Auto-Legion', branch: 'main',
    title: '던전 오토 레기온', eyebrow: '오토배틀러', category: 'web',
    description: '용병을 고용하고 진형을 꾸려 던전 끝까지 나아가는 웹 게임.',
    tags: ['JavaScript', '로그라이크', '게임'], icon: '⚔', tone: 'steel',
    preview: 'play/dungeon-auto-legion/index.html',
  },
  {
    id: 'gonu', repo: 'Gonu', branch: 'main',
    title: '고누', eyebrow: '전통 보드게임', category: 'web',
    description: '한국 전통 놀이 고누를 브라우저에서 즐길 수 있는 게임.',
    tags: ['JavaScript', '보드게임'], icon: '●', tone: 'blue',
    preview: 'play/gonu/index.html',
  },
  {
    id: 'k-worker', repo: 'k--', branch: 'main1',
    title: 'K-직장인 퇴사 시뮬레이터', eyebrow: '방치형 클리커', category: 'web',
    description: '목표 자금을 모아 사표를 던지는 유쾌한 직장인 클리커 게임.',
    tags: ['HTML', 'JavaScript', '게임'], icon: '⌁', tone: 'lime',
    preview: 'play/k-worker/index.html',
  },
  {
    id: 'web-game', repo: 'Web_Game', branch: 'main',
    title: 'Web Game', eyebrow: '초기 웹 게임', category: 'web',
    description: 'HTML, CSS, JavaScript로 만든 초기 웹 게임 프로젝트.',
    tags: ['HTML', 'CSS', 'JavaScript'], icon: '▣', tone: 'pink',
    preview: 'play/web-game/index.html',
  },
  {
    id: 'p-f', repo: 'P.F', branch: 'main',
    title: '작은 웹 실험들', eyebrow: '미니 프로젝트 모음', category: 'experiment',
    description: '계산기, 룰렛, 박스 피하기 등 여러 작은 웹 작업을 모은 기록.',
    tags: ['HTML', 'JavaScript', '실험'], icon: '✳', tone: 'lavender',
    preview: 'play/p-f/index.html',
  },
  {
    id: 'calculator-sample', repo: 'CalculatorSample', branch: 'master',
    title: 'Calculator Sample', eyebrow: 'Android 연습', category: 'experiment',
    description: 'Android 계산기 구현을 단계별로 연습한 초기 프로젝트.',
    tags: ['Android', 'Java', '샘플'], icon: '＋', tone: 'gray',
  },
];
